branch-defaults:
  master:
    environment: development
environment-defaults:
  development:
    branch: null
    repository: null
global:
  application_name: Hapi-Authentication
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: myProfile
  sc: git
